models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property integer $author_id
 * @property string  $date
 * @property string  $title
 * @property string  $preview
 * @property string  $detail
 * @property string  $created_at
 * @property string  $updated_at
 * @property integer $is_active
 */
class News extends \yii\db\ActiveRecord
{
    const DATE_FORMAT = 'Y-m-d H:i:s';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['author_id', 'is_active'], 'integer'],
            [['date', 'created_at', 'updated_at'], 'safe'],
            [['preview', 'detail'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['author_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'author_id'  => 'Автор',
            'date'       => 'Дата',
            'title'      => 'Заголовок',
            'preview'    => 'Анонс',
            'detail'     => 'Текст',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'is_active'  => 'Активность',
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            if (!$this->id) {
                $this->created_at = date(static::DATE_FORMAT);
                $this->updated_at = date(static::DATE_FORMAT);
                $this->author_id  = Yii::$app->user->getId();
            } else {
                $this->updated_at = date(static::DATE_FORMAT);
            }
        }

        return parent::beforeSave($insert);
    }


}

controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\models\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\AccessRule;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    array(
                        'allow' => true,
                        'actions' => array('index'),
                        'roles' => array('@', '?')
                    ),
                    array(
                        'allow' => true,
                        'actions' => array('view'),
                        'roles' => array('reguser')
                    ),
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new NewsSearch();
        $dataProvider = $searchModel->getActive();

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/news/_item.php
<?php
/**
 * @var $news \app\models\News
 */
?>
<div class="news_item">
    <h4 class="list-group-item-heading">
        <?php if (Yii::$app->user->isGuest) { ?><?=$news->title?>
        <?} else {?>
            <?php echo \yii\helpers\Html::a($news->title, ['news/view', 'id' => $news->id])?>
        <?}?>
    </h4>
    <p class="list-group-item-text"><?=$news->preview?></p>
</div>

views/news/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NewsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = 'Новости';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-9">
        <div class="news-index">

            <h1><?= Html::encode($this->title) ?></h1>
            <?php
            foreach ($dataProvider->models as $model) {
                echo $this->render('_item', [
                    'news' => $model
                ]);
            }

            echo LinkPager::widget([
                'pagination' => $dataProvider->getPagination(),
            ]);
            ?>

        </div>
    </div>
</div>

views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>


    <p><i><?=$model->preview?></i></p>

    <p><?=Html::encode($model->detail)?></p>

</div>